// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CashBird - Jogue, Voe, Ganhe",
  description: "O jogo mais viciante do Brasil! Aposte contra outros jogadores em partidas rápidas de CashBird e ganhe dinheiro real.",
  keywords: "jogo, aposta, dinheiro real, flappy bird, cashbird, competitivo",
  authors: [{ name: "CashBird Team" }],
  creator: "CashBird",
  publisher: "CashBird",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://cashbird.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: "CashBird - Jogue, Voe, Ganhe",
    description: "O jogo mais viciante do Brasil! Aposte contra outros jogadores e ganhe dinheiro real.",
    url: 'https://cashbird.com',
    siteName: 'CashBird',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'CashBird - Jogue, Voe, Ganhe',
      },
    ],
    locale: 'pt_BR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: "CashBird - Jogue, Voe, Ganhe",
    description: "O jogo mais viciante do Brasil! Aposte contra outros jogadores e ganhe dinheiro real.",
    images: ['/og-image.png'],
  },
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'CashBird',
  },
  other: {
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'CashBird',
    'application-name': 'CashBird',
    'msapplication-TileColor': '#FBBF24',
    'theme-color': '#FBBF24',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#FBBF24" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="CashBird" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}